name: Build AppImage and push to registry

on:
  workflow_dispatch:
  # release:
  #   types: [published]
  push:
    branches:
      '**'

jobs:
  appimage:
    name: Publish Join Point Clouds
    timeout-minutes: 30
    runs-on: buildjet-8vcpu-ubuntu-2204-arm

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build module
        run: make appimage TAG_VERSION="0.0.1"

      - name: Bundle module
        run: |
          mv viam-camera-join-point-clouds-latest-aarch64.AppImage viam-jpc.AppImage
          tar czf module.tar.gz viam-jpc.AppImage

      - name: Upload module
        uses: viamrobotics/upload-module@main
        with:
          platform: linux/arm64
          version: 0.0.1
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}
