name: Build AppImage and push to registry

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  appimage:
    name: Publish Join Point Clouds
    timeout-minutes: 30
    runs-on: buildjet-8vcpu-ubuntu-2204-arm
    container:
      image: ghcr.io/viamrobotics/viam-camera-realsense:arm64
      options: --platform linux/arm64

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build module
        run: make appimage TAG_VERSION="${{ github.ref_name }}"

      - name: Bundle module
        run: |
          make module.tar.gz

      - name: Upload module
        uses: viamrobotics/upload-module@main
        with:
          platform: ${{ github.ref_name }}
          version: 0.0.4
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}
